URL_CITY_FROM = "http://api.jne.co.id:8889/auto/api/list/key/"
URL_CITY_TO = "http://api.jne.co.id:8889/iframe/server/server_city.php"
URL_TARIFF = "http://api.jne.co.id:8889/api/price/list/"
URL_TRACKING = "http://api.jne.co.id:8889/api/tracking/list/cnote/"
URL_NEARBY = "http://api.jne.co.id:8889/maps/maps_track/map"
